### ISSUE TITLE
能不能增加 rss 地址一栏

### ISSUE THREAD

**Issue by GeBron** [relatos/techblog#1]

**Comment by ityouknow** [comment]
好的，后期考虑加进入。

**Comment by xmt1139057136** [comment]
网站名称：业余草
网站链接：http://www.xttblog.com
网站描述：业余草 的个人博客，分享技术，分享个人对社会的思考

**Comment by GeBron** [comment]
> 网站名称：业余草
> 网站链接：http://www.xttblog.com
> 网站描述：业余草 的个人博客，分享技术，分享个人对社会的思考

你应该提交PR
